### PR TITLE
Update the python version badge.

### PR DESCRIPTION
**Pull request by MaxJPRey**

### CODE REVIEW

**Comment by RobPasMue** [comment]
Hi @MaxJPRey! I think after the release for 0.2.0 (coming from my previous PR) this is no longer required since the Python badge will render properly (i.e. all Python versions supported).

Feel free to close the PR unless you really want to merge it as is.

image

**Comment by MaxJPRey** [comment]
> Hi @MaxJPRey! I think after the release for 0.2.0 (coming from my previous PR) this is no longer required since the Python badge will render properly (i.e. all Python versions supported).
> 
> Feel free to close the PR unless you really want to merge it as is.
> 
> image

No that works for me @RobPasMue . I will close it.

**Comment by MaxJPRey** [comment]
The python badge should be displayed properly in the next release 0.2.0. Closing the PR.

**Comment by MaxJPRey** [comment]
The python badge should be displayed properly in the next release 0.2.0. Closing the PR.

**Pull request closed without merging**
